### ISSUE TITLE
学校“更新历史”没有记录

### ISSUE THREAD

**Issue by jianhe7** [yannonghuang/shinshin#12]
以学校用户身份登陆学校#75， 更新了几个记录， 例如地址、学校状态、学校需求。以管理员身份登陆后，没有看到这些更新历史记录。

**Comment by yannonghuang** [comment]
there are readonly and edit modes, only in the latter mode can a user make changes. pls refresh code base & see if the pb is still there

**Comment by jianhe7** [comment]
I imported the new database, then I logged in as shinshin and updated the principal and contact for school #75, but still the update records do not list these two changes, but the school page shows the changes. 
<img width="422" alt="Screen Shot 2022-03-27 at 10 41 51 PM" src="https://user-images.githubusercontent.com/11562782/160333687-65ed1212-5b75-44e1-b742-262a90604301.png">

**Comment by yannonghuang** [comment]
<img width="1148" alt="Screen Shot 2022-03-27 at 10 53 45 PM" src="https://user-images.githubusercontent.com/93168805/160335068-b30956eb-6f06-40d7-b5fb-699b04b0e229.png">

**Comment by jianhe7** [comment]
Can you obtain the user's name using the id? It is hard to tell by looking at the update history what is changed. Nobody would know which user uses which id.

**Comment by jianhe7** [comment]
jian_teacher logged in to update the address for school #75 twice, but these are not in the update history, seen by the Admin "shinshin". The school page does show the updated address by jian_teacher, but the change records were not saved. This test was done without Apache.

**Comment by yannonghuang** [comment]
fixed

**Comment by jianhe7** [comment]
Works fine mostly. Please show school contact changes as names instead of showing contactIds, just as you did for principal.

**Comment by jianhe7** [comment]
why 失联 not in the dropdown list of school status? But it was the original status for school #75. 
<img width="252" alt="Screen Shot 2022-03-31 at 11 23 52 PM" src="https://user-images.githubusercontent.com/11562782/161207020-24942309-140b-4003-b8bd-ad29302e57ba.png">

**Comment by yannonghuang** [comment]
contact name is added to the change history. a new dump is needed.

**Comment by jianhe7** [comment]
I ported in the new dump, git pull and rebuilt the code, and restart the node server, but the contact name is not here. The update history still shows the contactId
<img width="488" alt="Screen Shot 2022-04-01 at 10 39 28 AM" src="https://user-images.githubusercontent.com/11562782/161314743-ff92a57e-19d4-40d3-bbc8-9c503b148e13.png">

**Comment by yannonghuang** [comment]
pls git-pull again

**Comment by yannonghuang** [comment]
失联 appears in the fuller list of school statuses accessible when login-ed in as a shinshin user.
