### ISSUE TITLE
新用户注册学校#75，输入校长名jian_yahoo, 出错

### ISSUE THREAD

**Issue by jianhe7** [yannonghuang/shinshin#14]
<img width="530" alt="Screen Shot 2022-03-27 at 11 22 23 PM" src="https://user-images.githubusercontent.com/11562782/160338415-fa778948-1d89-43ae-9ef2-a00a4afd57ce.png">

<img width="972" alt="Screen Shot 2022-03-27 at 11 21 18 PM" src="https://user-images.githubusercontent.com/11562782/160338449-b332c0ce-2e92-44f8-bc34-b255d29c3b66.png">

**Comment by jianhe7** [comment]
corrected to "jian_yahoo", still failed to login

**Comment by yannonghuang** [comment]
fixed. pls "edit" the school #75 to save "jian_yahoo" as principal.

**Comment by jianhe7** [comment]
I already made jian_yahoo as principal last time. 

I just did git pull and rebuilt the code again. jian_teacher couldn't register as the school user for #75 because entering "jian_yahoo" as principal still can't pass the check. Same error "校长姓名输入有误！"

**Comment by yannonghuang** [comment]
would you mind git-pulling again & rebuilding the code? added a few debugging lines, i could not reproduce locally. thx

**Comment by jianhe7** [comment]
[access_log.txt](https://github.com/yannonghuang/shinshin/files/8367603/access_log.txt)
[error_log.txt](https://github.com/yannonghuang/shinshin/files/8367604/error_log.txt)

Where did you output the debugging lines? I attach the apache/log files here.

**Comment by yannonghuang** [comment]
I have not tested the Apache configuration :-(

Is it possible to try the react/node combination first?

**Comment by Yiqing9** [comment]
Jian,

Yannong suggest that you use the same configuration as the  current development environment to do the test first. Otherwise it's hard to reproduce the issues you see.

**Comment by jianhe7** [comment]
Need to make sure all principal users migrated from the old SPM will be marked as the role "principal", otherwise, the same mistake may happen for school user registration. In this case, I re-tested this today with jian_yahoo, but it's not marked as the principal from the database import, so failed again.
